name: Template Build
on:
  repository_dispatch:
    types: [template_update]
env:
  BLOGA_CLIENT_ID:  ${{ secrets.BLOGA_CLIENT_ID }}
  BLOGA_CLIENT_SECRET:  ${{ secrets.BLOGA_CLIENT_SECRET }}
jobs:
  init:
    runs-on: ubuntu-latest
    # outpus result type is string, true will be "true"
    outputs:
      blogaAccessToken: ${{ steps.blogaAccessToken.outputs.result }}
      templateRepo: ${{ steps.templateRepo.outputs.result }}
      templateBranch: ${{ steps.templateBranch.outputs.result }}
      templateId: ${{ github.event.client_payload.template_id }}
    steps:        
      - id: blogaAccessTokenResponse
        name: get bloga access token response
        if: (env.BLOGA_CLIENT_ID) && (env.BLOGA_CLIENT_SECRET)
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1.4
        with:
            url: 'https://auth.owenyoung.com/api/v1/oauth/token'
            method: 'POST'
            headers: '{"Content-Type": "application/json"}'
            data: '{"client_id": "${{ env.BLOGA_CLIENT_ID }}","client_secret": "${{ env.BLOGA_CLIENT_SECRET }}","grant_type":"client_credentials"}'
      - id: blogaAccessToken
        name: get bloga access token
        if:  (steps.blogaAccessTokenResponse.outcome == 'success')
        uses: actions/github-script@v2
        env:
          RESPONSE: ${{ steps.blogaAccessTokenResponse.outputs.response }}
        with:
          script: |
            const response = JSON.parse(process.env.RESPONSE)
            if(response.data.access_token){
              return response.data.access_token
            }else{
              core.setFailed(`Can not get bloga access token`);
            }
          result-encoding: string
      - id: blogaTemplateResponse
        name: get bloga template response
        if: (github.event.client_payload.template_id)
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1.4
        with:
            url: https://api.bloga.owenyoung.com/api/v1/templates/${{ github.event.client_payload.template_id }}
            method: 'GET'
            headers: '{"Content-Type": "application/json"}'
      - id: templateRepo
        name: get template repo
        if: steps.blogaTemplateResponse.outcome == 'success'
        uses: actions/github-script@v2
        env:
          RESPONSE: ${{ steps.blogaTemplateResponse.outputs.response }}
        with:
          script: |
            const response = JSON.parse(process.env.RESPONSE)
            if(response.data && response.data.repo){
              return response.data.repo
            }else{
              return ""
            }
          result-encoding: string
      - id: templateBranch
        name: get template branch
        if: steps.blogaTemplateResponse.outcome == 'success'
        uses: actions/github-script@v2
        env:
          RESPONSE: ${{ steps.blogaTemplateResponse.outputs.response }}
        with:
          script: |
            const response = JSON.parse(process.env.RESPONSE)
            if(response.data && response.data.branch){
              return response.data.branch
            }else{
              return ""
            }
          result-encoding: string
      - id: isValidForBuild
        name: check if valid for build
        uses: actions/github-script@v2
        env:
          templateRepo: ${{ steps.templateRepo.outputs.result }}
          blogaAccessToken: ${{ steps.blogaAccessToken.outputs.result }}
        with:
          script: |
            if(process.env.templateRepo && process.env.blogaAccessToken){
              return true
            }else{
              return false
            }
          result-encoding: string 

  build:
    needs: init
    # if: (needs.init.outputs.isValidForBuild == 'true')
    runs-on: ubuntu-latest
    steps:
    - name: Dump INIT_OUTPUTS
      run: echo $INIT_OUTPUTS 
      env:
        INIT_OUTPUTS: ${{ toJson(needs.init.outputs) }}
    - name: checkout template repo
      uses: actions/checkout@v2
      with:
        repository: ${{ needs.init.outpus.templateRepo }}
        ref: ${{ needs.init.outpus.templateBranch }}
    - name: Yarn install
      run: 'yarn'
    - name: Add Bloga-gatsby dependence
      run: yarn add bloga-gatsby
    - name: Load bloga gatsby options
      run: ./node_modules/.bin/bloga-gatsby options --override --format json --path bloga-options-temp.json
    - id: blogaGatsbyOptions
      name: get bloga gatsby options
      run: echo "::set-output name=result::$(cat bloga-options-temp.json)"
    - name: post to bloga
      uses: CamiloGarciaLaRotta/watermelon-http-client@v1.4
      with:
          url: 'https://api.bloga.owenyoung.com/api/v1/templates/${{ needs.init.outputs.templateId }}'
          method: 'PATCH'
          headers: '{"Content-Type": "application/json","Authorization":"Bearer ${{ needs.init.outputs.blogaAccessToken }}"}'
          data: ${{steps.blogaGatsbyOptions.outputs.result}}